### ISSUE TITLE
Make patch releases not invalidate the configuration

### ISSUE THREAD

**Issue by sschuberth** [ecovaci/winfoom#17]
Currently, even patch-level releases invalidate the configuration, forcing the user to re-enter all data. How about following [semantic versioning](https://semver.org/) which guarantees that patch- and minor-level releases are backwards compatible and keep the configuration for those, and only invalidate the configuration for major-level version changes?

**Comment by sschuberth** [comment]
PS: If you're in need of a Java library for semantic versioning I can recommend https://github.com/vdurmont/semver4j.

**Comment by ecovaci** [comment]
I did not employed semantic versioning because it makes sense for libraries or anything that exposes an API, while Winfoom is a standalone desktop application. For example, according to semantic versioning, if a certain value from a configuration file is no longer in use and I want to remove it, the only way to do it is by releasing a major version even though there is no other change. 
I'll implement this simply by checking the compatibility between the existent config file and the new one. If compatible - keep it, overwrite otherwise.

**Comment by ecovaci** [comment]
Solved in v2.0.4

**Comment by sschuberth** [comment]
> I'll implement this simply by checking the compatibility between the existent config file and the new one. If compatible - keep it, overwrite otherwise.

Even better, thanks!
