### ISSUE TITLE
GUI-less mode

### ISSUE THREAD

**Issue by ecovaci** [ecovaci/winfoom#19]
**Is your feature request related to a problem? Please describe.**
Once the application is configured, there is no reason for GUI other than starting/stopping.

**Describe the solution you'd like**
The application should have the capability to be managed from command line only, without any graphical interface.

**Comment by timokd** [comment]
Hello Eugen,

I would change something in the description

Instead of writing:
Describe the solution you'd like
The application should have the capability to be managed from command line only, without any graphical interface.

I would write: 
Describe the solution you'd like
The application should be startable from command line without any graphical interface after it was parametrized via the gui.
Once the applilcation was opened via gui and all parameters are given. From now it can be started with Windows start via java -jar winfoom.jar "guiless". This should result that the small icon in taskbar notification area appears.

**Comment by ecovaci** [comment]
Actually, I almost finished an implementation that doesn't use GUI at all. It exposes an API accessible via HTTP (I also made a command line client to make this API easy to use) which allows configuration, start, stop, interrogation the current state etc. This way, the GUI mode becomes obsolete, although still possible. Hopefully by the end of this week I'll release this new version working on any UNIX based OS, not only Windows.

**Comment by timokd** [comment]
Wow, great news. Thank you a lot.

**Comment by ecovaci** [comment]
Solved in v3.0.1
